### ISSUE TITLE
Is skylink "down"...?

### ISSUE THREAD

**Issue by jennyyuejin** [Temasys/SkylinkJS#189]
Is skylink down today? Everything worked as expected when I ran the tutorial code locally last night. This morning the exact same code gave 2 errors -- 1. timed out while trying to reach api.temasys.com.sg/api ; 2. cross site error (didn't occur yesterday because I added local host to the whitelist on the api config page).

Is it common for skylink to be "down" like this?

**Comment by ncurrier** [comment]
skylink is not down, i have just verified that all services are working as expected and not showcasing any error state or connectivity issues. could you please open a support ticket at support.temasys.com.sg with details of your app key and any error you are experiencing so that we can take a look at what might be happening for your key and get you going again. there are certainly certain combinations of settings that can result a denied access state if certain conditions are not met which is what I suspect may be happening here.

**Comment by jennyyuejin** [comment]
Thanks for the lightning fast reply! Ticket submitted.
Forgot to say how amazing skylinkjs is! Takes the work out of wrestling with webRTC.

**Comment by ncurrier** [comment]
your welcome.

**Comment by jennyyuejin** [comment]
I was pulling my hair out for 2 days. And the day I found skylinkjs was like xmas!

**Comment by jennyyuejin** [comment]
Lavanya got back to me and fixed the issue:

The root of the issue seems to be a localised DDOS attack on our US West Coast datacenter. We have blocked the offending traffic and have brought up backup nodes.
