### ISSUE TITLE
Persistent Rooms

### ISSUE THREAD

**Issue by amangupta26** [Temasys/SkylinkJS#236]
Hi,
  What is meant by persistent rooms mentioned in the doc of `init` method 

```
credentials {JSON} Optional

The credentials configured for starting a new persistent room meeting or connecting with Application Keys that do not use CORS authentication. Setting the startDateTime or the duration will not affect the actual duration for non persistent rooms. 
```

Also, what is meant by non-persistant rooms. Are they purged after a certain time.

We have seen some cases when user could not get video and audio in a room after using the room for some time. Is this because rooms are non-persistent and we need to make them persistent?

**Comment by letchoo** [comment]
Hi @amangupta26,

Sorry for the late reply.

What is Persistent Room
----
The Persistent Room feature allows room contexts to be created based on scheduled times instead of active sessions. The scheduling of which is done via the SDK methods or direct REST API calls. Any given key can support either dynamic or persistent rooms but not both. This option can be changed at any time however changing it from persistent to dynamic will destroy any currently schedule room contexts.
 
Room sessions from a Persistent Room is a scheduled session.
 
How to setup the Persistent Room feature
----
**1. Configure the Application Key persistent flag**
This will configure all the Rooms tied to the Application Key as Persistent.

![image](https://cloud.githubusercontent.com/assets/4675614/16040427/0912e186-3262-11e6-9aeb-373c3bf97cee.png)

**2. Create scheduled sessions for specific rooms**
You can create a scheduled session by doing a REST call by POST to the Meeting Resources API.
([See Create Meeting Resources API doc](https://temasys.atlassian.net/wiki/display/TPD/SkylinkAPI+-+Meeting+%28Persistent+Room%29+Resources#SkylinkAPI-Meeting(PersistentRoom)Resources-POST/rest/meetings/))
 
From here as suggestion, in UI standpoint of view, it can be displayed as creating a scheduled video/audio call meeting. 
 
**3. Retrieve scheduled sessions**
You can retrieve the all the created scheduled sessions by doing a REST call by GET to the Meeting Resources API.
There are two types of REST calls that allows you to retrieve scheduled sessions for a specific room or scheduled sessions for all rooms in an Application Key.
([See Retrieve (for specific Room) Meeting Resources API doc](https://temasys.atlassian.net/wiki/display/TPD/SkylinkAPI+-+Meeting+%28Persistent+Room%29+Resources#SkylinkAPI-Meeting(PersistentRoom)Resources-GET/rest/meetings/:apiKey/:room))
([See Retrieve (for all Rooms) Meeting Resources API doc](https://temasys.atlassian.net/wiki/display/TPD/SkylinkAPI+-+Meeting+%28Persistent+Room%29+Resources#SkylinkAPI-Meeting(PersistentRoom)Resources-GET/rest/meetings/:apiKey))
 
From here as suggestion, in UI standpoint of view, it can be displayed as the list of scheduled video/audio call meetings as calendar or list.
 
**4. Delete scheduled sessions (optional)**
You can delete created schedules session by doing a REST call by DELETE to the Meeting Resources API.
([See Delete Meeting Resources API doc](https://temasys.atlassian.net/wiki/display/TPD/SkylinkAPI+-+Meeting+%28Persistent+Room%29+Resources#SkylinkAPI-Meeting(PersistentRoom)Resources-DELETE/rest/meetings/:mid))
 
From here as suggestion, in UI standpoint of view, it can be displayed as a cancel (or delete) button for the meeting item.
 
**5. Starting the scheduled session call**
You can start the scheduled Room session by authenticating the connection via credentials format as found in the guide [here](http://support.temasys.com.sg/support/solutions/articles/12000002712-authenticating-your-application-key-to-start-a-connection).
 
You will need to provide the `duration`, `startDateTime` stamp and the generated `credentials` based off the Application Key `secret`, `duration` and `startDateTime` stamp.
 
 
What are the scenarios for scheduled Room session
----
- a. Joining the Room without any scheduled sessions going on
The [`systemAction`](http://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_systemAction) event triggers an action of `SYSTEM_ACTION.REJECT` and reason of `SYSTEM_ACTION_REASON.EXPIRED`.
- b. While in a scheduled Room session, and session is expiring
The [`systemAction`](http://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_systemAction) event triggers an action of `SYSTEM_ACTION.WARNING` and reason of `SYSTEM_ACTION_REASON.ROOM_CLOSING`.
- c. While in a scheduled Room session, and session has expired
The [`systemAction`](http://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_systemAction) event triggers an action of `SYSTEM_ACTION.REJECT` and reason of `SYSTEM_ACTION_REASON.ROOM_CLOSED`.
 
 
What is the difference between scheduled and non-scheduled Room sessions?
----
Connection started from scheduled Room sessions checks if there is any records that matches the given `duration`, `startDateTime` and `credentials` in the database (that is created with the Meeting Resources API). If there is not any, it will not start the connection.

Whereas connection started from non-scheduled Room sessions does not require checking of the `duration`, `startDateTime` and `credentials` but starts the connection immediately based off the given configuration (whether the authentication is credentials format or CORS format).
 
([See all of the Meeting Resources API doc](https://temasys.atlassian.net/wiki/display/TPD/SkylinkAPI+-+Meeting+(Persistent+Room)+Resources))
