### ISSUE TITLE
New Code Suggests Way to Select Rear Camera in IOS Safari?

### ISSUE THREAD

**Issue by VikR0001** [Temasys/SkylinkJS#331]
I am **loving** Temasys and Skylink and am using it in the app I am developing!

I have Skylink code to select another camera, that works on OS X Chrome, but does not yet work on OS X Safari, OS X Firefox, or IOS Safari.

From the [docs for Skylink](https://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_getUserMedia):

> // Example 6: Configure video and audio based on selected sources. **Does not work for Firefox currently.**

But new non-Skylink code has recently been posted on webrtc.github.io, that DOES successfully select any connected video camera on OS X Firefox and OS X Safari and can even select the rear camera on IOS Safari!

https://webrtc.github.io/samples/src/content/devices/input-output/

Would it be possible to update Skylink to use these successful techniques?

Thanks in advance for your support!

**Comment by VikR0001** [comment]
UPDATE: Here's a codepen we can work with. 

https://codepen.io/VikR/pen/WKpjYq

**Comment by geekavi** [comment]
We are looking into it. We will be updating you soon.

**Comment by VikR0001** [comment]
Fantastic. Thanks very much!

**Comment by VikR0001** [comment]
I just updated the Codepen.

**Comment by ishannaithani** [comment]
Hi @VikR0001, 

Thanks for reaching out and we are glad to hear that you love us! Please checkout this codepen: [https://codepen.io/ishannaithani/pen/vaJRZW](https://codepen.io/ishannaithani/pen/vaJRZW)

I have made some changes in your JavaScript code - mainly returning a `promise` from the `enumerateDevices` method. For FireFox, though there is a small change in the SDK required (The changed SDK is the one that codepen example is pulling but not in master right now). 

For Safari, it seems that enumerateDevices needs to be called again so that the correct labels of devices can be fetched. I have tested the codepen on OSX Chrome, OSX Safari, OSX FireFox. 

Do let me know if the example solves your issues (and we can discuss on how to get this change released).

**Comment by VikR0001** [comment]
Hi @ishannaithani.  Fantastic! I find it is now working on OS X Safari, OS X Firefox and IOS Safari! Congratulations!

What is the next step to getting this change released?

**Comment by VikR0001** [comment]
I just tested the new release, SkylinkJS 0.6.34, with OS X Safari and with IOS Safari. It worked. Awesome!
